version: '2'
services:
  servbuild:
    build: .
    volumes:
      - data_volume:/opt/boxfuse-sample-java-war-hello/target/
  servprod:
    image: tomcat:9
    ports:
      - "8080:8080"
    volumes:
      - data_volume:/usr/local/tomcat/webapps/
volumes:
  data_volume: