version: '2'
services:
  servbuild:
    build: .
    volumes:
      - /tmp:/opt/
  servprod:
    image: tomcat:9
    depends_on:
      - servbuild
    ports:
      - "8080:8080"
    volumes:
      - /tmp/boxfuse-sample-java-war-hello/target/:/usr/local/tomcat/webapps/