---
version: '2'
services:
  servbuild:
    image: ubuntu:latest
#    links:
#      - php
#    volumes:
#      - ./nginx.conf:/etc/nginx/conf.d/default.conf
#    volumes_from:
#      - php
  servprod:
    image: tomcat:9.0
#    environment:
#     - TYPO3_CONTEXT=Development/Docker
#    links:
#      - db
#      - redis
    ports:
      - "8080:80"
#    volumes:
#      - ./htdocs:/var/lib/tomcat9/webapps/
---