---
version: '2'
services:
  servbuild:
    build: .
    volumes:
     # - ./src:/opt/app
      - /tmp:/opt/boxfuse-sample-java-war-hello/target/
  servprod:
    image: tomcat:9.0.20-jre8-alpine
    ports:
      - "8080:8080"
    volumes:
      - /tmp:/usr/local/tomcat/webapps/
---



